apiVersion: operator.glsboperator.io/v1beta1
kind: GSLBPool
spec:
  globalName: mypool.domain.ru
  balanceType: wrr
  monitor:
    type: http
    tls:
      enabled: true
      skipVerify: true
    port: 443
    hostname: customerdomain.com
    urlPath: /health
  members:
    - name: ip1
      ip: 1.1.1.1
      weight: 1
    - name: ip2
      ip: 2.2.2.2
      weight: 1
    
